language: python
sudo: false
cache:
  directories:
    - node_modules
    - .pip_download_cache
    - "$HOME/virtualenv/python2.7.9"
env:
  global:
    - PIP_DOWNLOAD_CACHE=".pip_download_cache"
python:
  - "3.2"
  - "3.3"
  - "3.4"
install:
  - time make
script:
  - make lint
  - py.test --cov raven_aiohttp --cov-report term-missing
