language: python
sudo: false
cache:
  directories:
    - node_modules
    - .pip_download_cache
    - "$HOME/virtualenv/python2.7.9"
env:
  global:
    - PIP_DOWNLOAD_CACHE=".pip_download_cache"
python:
  - "3.4"
  - "3.5"
install:
  - time make
script:
  - time make lint-python
  - time make test-python
